### ISSUE TITLE
NAN problem when fit MovieReview datasets

### ISSUE THREAD

**Issue by haiahaiah** [kaize0409/HyperGAT#2]
When I use your model to fit MoviewReview datasets which is from [TextGCN](https://github.com/chengsen/PyTorch_TextGCN/tree/main/data/text_dataset). I met problem as follows. Thanks a lot in advance~

min_len_of_sentence : 0
max_len_of_sentence : 27
min_num_of_sentence : 1
max_num_of_sentence : 5
average_len_of_sentence: 9.062759575449931
average_num_of_sentence: 1.0162258488088538
Total_num_of_sentence : 10835
Counter({'1': 5331, '0': 5331})
Total_number_of_words: 4284
Total_number_of_categories: 2
-------------------------------------------------------
epoch:  0
start training:  2020-12-16 16:58:18.184139
Traceback (most recent call last):                                    
  File "run.py", line 109, in <module>
    main()
  File "run.py", line 82, in main
    train_model(model, train_data, args)
  File "/data/yuhai/tc/HyperGAT/model.py", line 114, in train_model
    targets, scores = forward(model, alias_inputs, HT, items, targets, node_masks)
  File "/data/yuhai/tc/HyperGAT/model.py", line 98, in forward
    node = model(items, HT)
  File "/home/yuhai/workspace/anaconda3/envs/torch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/tc/HyperGAT/model.py", line 89, in forward
    nodes = self.hgnn(hidden, HT)
  File "/home/yuhai/workspace/anaconda3/envs/torch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/tc/HyperGAT/model.py", line 40, in forward
    x = self.gat2(x, H)
  File "/home/yuhai/workspace/anaconda3/envs/torch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/tc/HyperGAT/layers.py", line 102, in forward
    assert not torch.isnan(pair_e).any()
AssertionError

**Comment by kaize0409** [comment]
fixed

**Comment by 1225993807** [comment]
Hello,i use a different dataset and also meet this problem. The gradient becomes NAN suddenly and nn.utils.clip_grad_norm is not working, how to fix this problem?
